spring.application.name=my_chef_now

spring.datasource.url=jdbc:postgresql://localhost:5555/mychefnow_db
spring.datasource.username=postgres
spring.datasource.password=Pass@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect